import './globals.css'
import type {Metadata} from 'next'
import Header from "@/components/Header/Header";
import {UserProvider} from '@auth0/nextjs-auth0/client';
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import ReduxProvider from "@/redux/provider";


export const metadata: Metadata = {
    title: 'Rick & Morty App',
    description: 'Generated by create next app',
    icons: {
        icon: "/icon.ico"
    }
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <UserProvider>
            <ReduxProvider>
                <AuthProvider>
                    <Header/>
                    {children}
                </AuthProvider>
            </ReduxProvider>
        </UserProvider>
        </body>
        </html>
    )
}
